// 백엔드 연동 전까지 사용하는 더미데이터.
export const MOCK_CLIENTS = [
    {
        id: '1',
        caregiverId: '4',
        name: '박영희',
        age: 77,
        gender: 'FEMALE',
        address: '청주시 흥덕구 사직동 45',
        mainDisease: '고혈압, 당뇨',
        phone: '010-2001-0001',
        familyContactName: '박서준',
        familyRelation: '자녀',
        familyContactPhone: '010-3001-0001',
        caregiverName: '김민지',
    },
    {
        id: '2',
        caregiverId: '4',
        name: '이순자',
        age: 83,
        gender: 'FEMALE',
        address: '청주시 흥덕구 서운동 123',
        mainDisease: '치매 초기',
        phone: '010-2001-0002',
        familyContactName: '이민호',
        familyRelation: '자녀',
        familyContactPhone: '010-3001-0002',
        caregiverName: '김민지',
    },
    {
        id: '3',
        caregiverId: '4',
        name: '정대호',
        age: 79,
        gender: 'MALE',
        address: '청주시 흥덕구 봉명동 12',
        mainDisease: '뇌졸중 후유증',
        phone: '010-2001-0003',
        familyContactName: '정하나',
        familyRelation: '배우자',
        familyContactPhone: '010-3001-0003',
        caregiverName: '김민지',
    },
    {
        id: '4',
        caregiverId: '4',
        name: '최옥순',
        age: 75,
        gender: 'FEMALE',
        address: '청주시 흥덕구 가경동 89',
        mainDisease: '고혈압',
        phone: '010-2001-0004',
        familyContactName: '최우진',
        familyRelation: '자녀',
        familyContactPhone: '010-3001-0004',
        caregiverName: '김민지',
    },
    {
        id: '5',
        caregiverId: '4',
        name: '강순희',
        age: 81,
        gender: 'FEMALE',
        address: '청주시 흥덕구 강서동 5',
        mainDisease: '당뇨',
        phone: '010-2001-0005',
        familyContactName: '강지원',
        familyRelation: '형제자매',
        familyContactPhone: '010-3001-0005',
        caregiverName: '김민지',
    },
    {
        id: '6',
        caregiverId: '4',
        name: '윤기철',
        age: 85,
        gender: 'MALE',
        address: '청주시 흥덕구 복대동 34',
        mainDisease: '파킨슨병',
        phone: '010-2001-0006',
        familyContactName: '윤소연',
        familyRelation: '배우자',
        familyContactPhone: '010-3001-0006',
        caregiverName: '김민지',
    },
    {
        id: '7',
        caregiverId: '4',
        name: '김성호',
        age: 81,
        gender: 'MALE',
        address: '청주시 흥덕구 복대동 67',
        mainDisease: '고지혈증',
        phone: '010-2001-0007',
        familyContactName: '김도윤',
        familyRelation: '자녀',
        familyContactPhone: '010-3001-0007',
        caregiverName: '김민지',
    },
    {
        id: '8',
        caregiverId: '4',
        name: '최화자',
        age: 79,
        gender: 'FEMALE',
        address: '청주시 흥덕구 신전동 21',
        mainDisease: '골다공증',
        phone: '010-2001-0008',
        familyContactName: '최시윤',
        familyRelation: '자녀',
        familyContactPhone: '010-3001-0008',
        caregiverName: '김민지',
    },
    {
        id: '9',
        caregiverId: '4',
        name: '오달수',
        age: 77,
        gender: 'MALE',
        address: '청주시 흥덕구 가경동 89',
        mainDisease: '고혈압',
        phone: '010-2001-0009',
        familyContactName: '오은비',
        familyRelation: '배우자',
        familyContactPhone: '010-3001-0009',
        caregiverName: '김민지',
    },
];