// 백엔드 연동 전까지 사용하는 더미데이터.
export const MOCK_CONSULTATIONS = [
    {
        id: '1',
        recipientName: '박영희',
        recipientAge: 77,
        caregiverName: '김민지',
        consultedAt: '2026-05-26T10:45:00',
        audioUrl: null,
        status: 'SPECIAL_NOTE',
        riskScore: 78,
        aiTags: ['식사감소', '우울감'],
        sttText: '어르신 요즘 밥은 좀 드세요? 밥이 영 입에 안 맞아요. 어제도 조금밖에 못 먹었어요.',
        aiSummary: '박영희 어르신은 최근 식욕 저하로 식사를 거의 못 하고 있으며 혼자 식사하는 것에 대한 외로움을 표현하셨음.',
        aiSummaryPreview: '식사 못 드신다 하셨으며 기분이 많이 처지고...',
        workerFinalNote: '어르신 식사 문제 지속. 가족 연계 필요성 체크.',
        socialWorkerOpinion: '식사 거부와 외로움 표현 동시 증가. 가족 연락 및 지역사회 연계 프로그램 참여 검토 권고.',
    },
    {
        id: '2',
        recipientName: '이순자',
        recipientAge: 83,
        caregiverName: '김민지',
        consultedAt: '2026-05-26T09:12:00',
        audioUrl: null,
        status: 'SPECIAL_NOTE',
        riskScore: 74,
        aiTags: ['반복발화'],
        sttText: '오늘도 예전 이야기를 반복해서 하셨고, 방금 얘기한 걸 또 물어보시는 모습을 보였음.',
        aiSummary: '이순자 어르신은 동일한 이야기를 반복하는 발화 패턴이 지속되었으며, 단기 기억력 저하로 보이는 모습이 관찰됨.',
        aiSummaryPreview: '오늘도 예전 이야기 반복하셨으며 이름을...',
        workerFinalNote: '반복 발화 및 기억 혼돈 증상 재확인.',
        socialWorkerOpinion: '반복 발화·기억 혼동 증가 추세. 인지기능 선별검사 연계 검토 필요.',
    },
    {
        id: '3',
        recipientName: '정대호',
        recipientAge: 79,
        caregiverName: '이성희',
        consultedAt: '2026-05-25T14:00:00',
        audioUrl: null,
        status: 'SPECIAL_NOTE',
        riskScore: 70,
        aiTags: ['낙상위험', '병원동행필요'],
        sttText: '어제 화장실 가다가 넘어질 뻔했다고 하심. 요즘 밤에 잠도 잘 못 잔다고 하심.',
        aiSummary: '정대호 어르신은 어제 낙상 위험 상황이 있었음을 언급하셨고, 수면장애도 지속되고 있음.',
        aiSummaryPreview: '어제 화장실 가다 넘어질 뻔 했다고 하심...',
        workerFinalNote: null,
        socialWorkerOpinion: '낙상 위험 재확인 필요. 안전 손잡이 설치 등 환경 점검 권고.',
    },
    {
        id: '4',
        recipientName: '최옥순',
        recipientAge: 75,
        caregiverName: '이성희',
        consultedAt: '2026-05-25T11:30:00',
        audioUrl: null,
        status: 'NEED_REVIEW',
        riskScore: 45,
        aiTags: ['약복용'],
        sttText: '어제 저녁 약을 깜빡하셨다고 하심. 오늘 아침 약은 챙겨 드셨음.',
        aiSummary: '최옥순 어르신은 어제 저녁 복약을 놓치신 것으로 확인됨.',
        aiSummaryPreview: '약을 어제 저녁에 깜빡하셨다고 하심...',
        workerFinalNote: null,
        socialWorkerOpinion: null,
    },
    {
        id: '5',
        recipientName: '강순희',
        recipientAge: 81,
        caregiverName: '박지수',
        consultedAt: '2026-05-24T14:10:00',
        audioUrl: null,
        status: 'NEED_REVIEW',
        riskScore: 42,
        aiTags: ['우울감'],
        sttText: '요즘 들어 기분이 처진다고 하심. 예전만큼 이웃들과 어울리지 않는다고 하심.',
        aiSummary: '강순희 어르신은 최근 우울감 표현이 증가하는 추세이며, 사회적 교류가 줄어든 것으로 확인됨.',
        aiSummaryPreview: '요즘 들어 기분이 처진다고 하셨으며...',
        workerFinalNote: null,
        socialWorkerOpinion: null,
    },
    {
        id: '6',
        recipientName: '김성호',
        recipientAge: 81,
        caregiverName: '박지수',
        consultedAt: '2026-05-24T11:00:00',
        audioUrl: null,
        status: 'NORMAL',
        riskScore: 12,
        aiTags: [],
        sttText: '건강 상태는 양호하다고 하심. 혈압도 정상 범위로 확인됨.',
        aiSummary: '김성호 어르신은 전반적으로 건강 상태 양호하며 혈압 정상 범위 확인됨. 특이사항 없음.',
        aiSummaryPreview: '건강 상태 양호. 혈압 정상 범위 확인...',
        workerFinalNote: '특이사항 없음. 정기 방문 지속.',
        socialWorkerOpinion: null,
    },
    {
        id: '7',
        recipientName: '최화자',
        recipientAge: 79,
        caregiverName: '김민지',
        consultedAt: '2026-05-23T10:30:00',
        audioUrl: null,
        status: 'NORMAL',
        riskScore: 8,
        aiTags: [],
        sttText: '전반적으로 양호하며 이웃과 잘 지낸다고 하심.',
        aiSummary: '최화자 어르신은 전반적으로 양호하며 이웃과의 교류도 원활한 것으로 확인됨.',
        aiSummaryPreview: '전반적으로 양호. 이웃과 잘 지낸다고 하심...',
        workerFinalNote: '특이사항 없음.',
        socialWorkerOpinion: null,
    },
    {
        id: '8',
        recipientName: '윤기철',
        recipientAge: 85,
        caregiverName: '김민지',
        consultedAt: '2026-05-23T09:00:00',
        audioUrl: null,
        status: 'NEED_REVIEW',
        riskScore: 38,
        aiTags: ['식사감소'],
        sttText: '식욕이 없다고 하셨으며 점심을 조금밖에 안 드셨음.',
        aiSummary: '윤기철 어르신은 식욕 감소가 지속되고 있으며 체중 변화 여부 확인이 필요함.',
        aiSummaryPreview: '식욕이 없다고 하셨으며 점심을 조금...',
        workerFinalNote: '식욕 감소 추이 지속 확인.',
        socialWorkerOpinion: null,
    },
    {
        id: '9',
        recipientName: '오달수',
        recipientAge: 77,
        caregiverName: '박지수',
        consultedAt: '2026-05-22T15:20:00',
        audioUrl: null,
        status: 'NORMAL',
        riskScore: 5,
        aiTags: [],
        sttText: '활력징후 모두 정상이었으며 기분 좋다고 하심.',
        aiSummary: '오달수 어르신은 활력징후 모두 정상이며 정서 상태도 양호한 것으로 확인됨.',
        aiSummaryPreview: '활력징후 모두 정상. 기분 좋다고 하심...',
        workerFinalNote: '특이사항 없음.',
        socialWorkerOpinion: null,
    },
    {
        id: '10',
        recipientName: '한복순',
        recipientAge: 80,
        caregiverName: '김민지',
        consultedAt: '2026-05-22T13:00:00',
        audioUrl: null,
        status: 'NEED_REVIEW',
        riskScore: 33,
        aiTags: ['수면문제'],
        sttText: '밤에 잠을 잘 못 잔다고 하셨으며 자주 깬다고 하심.',
        aiSummary: '한복순 어르신은 수면 불규칙 패턴이 확인되었으며 지속적인 관찰이 필요함.',
        aiSummaryPreview: '밤에 잠을 잘 못 잔다고 하셨으며...',
        workerFinalNote: null,
        socialWorkerOpinion: null,
    },
];